### ISSUE TITLE
Helm chart index.yaml

### ISSUE THREAD

**Issue by filippolmt** [traccar/traccar-helm#10]
hi @tananaev could you follow these instructions: https://github.com/helm/chart-releaser-action , you should create a branch with the name gh-pages in order to create the index.yaml file

**Comment by tananaev** [comment]
Does the branch need to be from master or just empty branch?

**Comment by filippolmt** [comment]
from what I have read and understood an empty branch would be needed.

**Comment by tananaev** [comment]
Done.
