### ISSUE TITLE
Horizontal Scaling

### ISSUE THREAD

**Issue by filippolmt** [traccar/traccar-helm#15]
Hi @tananaev , I would like to update the chart to support the new traccar configuration for horizontal scaling, I would like to understand if this configuration is on by default and does not need multicast to be configured.

From what I understand and read on the documentation the multicast is only for the GUI cache, if this is not configured is it still possible to horizontally scale the pods?

**Comment by tananaev** [comment]
It's not enabled by default. You need to add some configuration parameters. It also requires that multicast is enabled on the network between pods.

**Comment by filippolmt** [comment]
sorry to continue with the questions, but in addition to wanting to change the configuration I want to understand something important to me.

I have an installation of traccar on my personal server, installed with helm chart, if I didn't configure multicast and especially didn't use the GUI could I still scale it without having problems? In the old versions of traccar it was not possible to do this.

I only use the API of traccar. 

Translated with www.DeepL.com/Translator (free version)

**Comment by tananaev** [comment]
Multicast is required to synchronize between servers. It is required for API to work correctly as well.

**Comment by filippolmt** [comment]
Hi @tananaev , I am trying to make the configuration, but I ran into two major problems:

1. is the broadcast interface mandatory? in a bit it is not so simple to specify interface
2. I created a broadcast service, if contacted it returns me all the IPs of the connected pods, the problem is that it doesn't have an IP address, to contact it necessarily needs a DNS

**Comment by tananaev** [comment]
1. Interface is not mandatory, as far as I remember.
2. Not sure what is the problem here.

**Comment by filippolmt** [comment]
Maybe I'm a little confused about this new feature,

what I haven't figured out yet is:

1. Is the multicast service an external service (at this point I think so)? 
2. If the first question is true, is there something ready-made? 
3. Always if the first question is true, do I have to reach it through IP address? (I'm asking because if I wanted to deploy something on the kubenretes cluster it's difficult to manage IPs)

**Comment by filippolmt** [comment]
Doing multicast on kubernetes is not simple at all, this is a bare-metal solution, if the only solution currently available for caching is this I don't think it is possible to implement it.

In case it is possible to use some other service I might try to configure it.

**Comment by tananaev** [comment]
There's an interface that can be implemented, so instead of multicast you can have something else.

**Comment by filippolmt** [comment]
If other solutions are available kindly tell me, otherwise I wouldn't know how to do it.

**Comment by tananaev** [comment]
You need to implement this interface:

https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/broadcast/BroadcastService.java
