### ISSUE TITLE
DNS Mysql

### ISSUE THREAD

**Issue by filippolmt** [traccar/traccar-helm#4]
Hi, I noticed that in the configMap exactly in the database connection part traccar.fullname is used, unfortunately this creates a problem in the deployment, if the release with name test is deploied, this will generate in the configMap test-traccar-mysql but the service of the mysql is called test-mysql, the pod will never be able to start because it will contact the wrong DNS.

`
 <entry key='database.url'>jdbc:mysql://{{ include "traccar.fullname" . }}-mysql:3306/{{ .Values.mysql.auth.database }}?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
`

**Comment by tananaev** [comment]
@kondas any thoughts?

**Comment by filippolmt** [comment]
If I can give you some advice, I would add a default variable MYSQL DNS
and I would add in the configMap {{.Release.Name}} - mysql which viele added if and only if MYSQL_DNS is not set.

**Comment by kondas** [comment]
Hi @filippolmt ,thanks for reporting. Can You provide me the full install command, and the values file for the install to reproduce?

**Comment by filippolmt** [comment]
Hi @kondas below executed the command: helm install my-traccar traccar/traccar --set mysql.enabled=true

**Comment by filippolmt** [comment]
I just tried again and it seems to go, I probably played too much with the configurations, sorry, if I should happen again I will reopen the issue.
